function setupModelInputTab(parentTab)
    % Dropdown for pre-set examples
    uicontrol('Parent', parentTab, 'Style', 'text', 'String', 'Select Pre-Set Example:', ...
        'Units', 'normalized', 'Position', [0.05, 0.92, 0.2, 0.04], 'HorizontalAlignment', 'right');
    hExampleDropdown = uicontrol('Parent', parentTab, 'Style', 'popupmenu', ...
        'String', {'Custom', 'Inverted Pendulum', 'Mass-Spring-Damper', 'DC Motor', ...
                   'First-Order System', 'Second-Order Underdamped', 'PID-Tuned System'}, ...
        'Units', 'normalized', 'Position', [0.27, 0.92, 0.6, 0.05], ...
        'Callback', @(src, event) loadPreSetExample(src, hNumEdit, hDenEdit, hKpEdit, hKiEdit, hKdEdit));

    % Transfer function input
    uicontrol('Parent', parentTab, 'Style', 'text', 'String', 'Numerator Coefficients:', ...
        'Units', 'normalized', 'Position', [0.05, 0.85, 0.2, 0.05], 'HorizontalAlignment', 'right');
    hNumEdit = uicontrol('Parent', parentTab, 'Style', 'edit', 'String', '', ...
        'Units', 'normalized', 'Position', [0.27, 0.85, 0.6, 0.05]);

    uicontrol('Parent', parentTab, 'Style', 'text', 'String', 'Denominator Coefficients:', ...
        'Units', 'normalized', 'Position', [0.05, 0.75, 0.2, 0.05], 'HorizontalAlignment', 'right');
    hDenEdit = uicontrol('Parent', parentTab, 'Style', 'edit', 'String', '', ...
        'Units', 'normalized', 'Position', [0.27, 0.75, 0.6, 0.05]);

    % Preview button
    uicontrol('Parent', parentTab, 'Style', 'pushbutton', 'String', 'Preview Transfer Function', ...
        'Units', 'normalized', 'Position', [0.05, 0.65, 0.4, 0.05], ...
        'Callback', @(src, event) previewTransferFunction(hNumEdit, hDenEdit, hTFAxes, hErrorMsg));

    % Error message display
    hErrorMsg = uicontrol('Parent', parentTab, 'Style', 'text', 'String', '', ...
        'Units', 'normalized', 'Position', [0.05, 0.4, 0.9, 0.05], ...
        'HorizontalAlignment', 'left', 'ForegroundColor', 'red');

    % Plot buttons
    uicontrol('Parent', parentTab, 'Style', 'pushbutton', 'String', 'Plot', ...
        'Units', 'normalized', 'Position', [0.55, 0.65, 0.15, 0.05], ...
        'Callback', @(src, event) plotCallback(sys, figHandles));

    uicontrol('Parent', parentTab, 'Style', 'pushbutton', 'String', 'Close Plots', ...
        'Units', 'normalized', 'Position', [0.75, 0.65, 0.15, 0.05], ...
        'Callback', @(src, event) closePlotsCallback(figHandles));
end
