function setupControllerDesignTab(parentTab)
    % PID Controller Inputs
    uicontrol('Parent', parentTab, 'Style', 'text', 'String', 'Kp:', ...
        'Units', 'normalized', 'Position', [0.05, 0.75, 0.1, 0.05], 'HorizontalAlignment', 'right');
    hKpEdit = uicontrol('Parent', parentTab, 'Style', 'edit', 'String', '1', ...
        'Units', 'normalized', 'Position', [0.17, 0.75, 0.1, 0.05]);

    uicontrol('Parent', parentTab, 'Style', 'text', 'String', 'Ki:', ...
        'Units', 'normalized', 'Position', [0.3, 0.75, 0.1, 0.05], 'HorizontalAlignment', 'right');
    hKiEdit = uicontrol('Parent', parentTab, 'Style', 'edit', 'String', '0', ...
        'Units', 'normalized', 'Position', [0.42, 0.75, 0.1, 0.05]);

    uicontrol('Parent', parentTab, 'Style', 'text', 'String', 'Kd:', ...
        'Units', 'normalized', 'Position', [0.55, 0.75, 0.1, 0.05], 'HorizontalAlignment', 'right');
    hKdEdit = uicontrol('Parent', parentTab, 'Style', 'edit', 'String', '0', ...
        'Units', 'normalized', 'Position', [0.67, 0.75, 0.1, 0.05]);

    % Optimize Button
    uicontrol('Parent', parentTab, 'Style', 'pushbutton', 'String', 'Optimize PID', ...
        'Units', 'normalized', 'Position', [0.8, 0.75, 0.15, 0.05], 'Callback', ...
        @(src, event) optimizePID(hKpEdit, hKiEdit, hKdEdit));
end
