function setupModelInputTab(parentTab)
    % Transfer Function Inputs
    uicontrol('Parent', parentTab, 'Style', 'text', 'String', 'Numerator Coefficients:', ...
        'Units', 'normalized', 'Position', [0.05, 0.85, 0.2, 0.05], 'HorizontalAlignment', 'right');
    hNumEdit = uicontrol('Parent', parentTab, 'Style', 'edit', 'String', '', ...
        'Units', 'normalized', 'Position', [0.27, 0.85, 0.6, 0.05]);

    uicontrol('Parent', parentTab, 'Style', 'text', 'String', 'Denominator Coefficients:', ...
        'Units', 'normalized', 'Position', [0.05, 0.75, 0.2, 0.05], 'HorizontalAlignment', 'right');
    hDenEdit = uicontrol('Parent', parentTab, 'Style', 'edit', 'String', '', ...
        'Units', 'normalized', 'Position', [0.27, 0.75, 0.6, 0.05]);

    % Preview Button
    uicontrol('Parent', parentTab, 'Style', 'pushbutton', 'String', 'Preview Transfer Function', ...
        'Units', 'normalized', 'Position', [0.05, 0.65, 0.4, 0.05], 'Callback', ...
        @(src, event) previewTransferFunction(hNumEdit, hDenEdit));
end
